### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by MichKael** [electricjs/electric#112]
Please i have this issue when i execute `electric run`.
Here is the complete error

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
I'm on Electric-CLI 2.4.2
please could someone help me?

**Comment by Robert-Frampton** [comment]
Hey @MichKael,

Do you have java installed?

**Comment by zenorocha** [comment]
That's correct, you need Java installed in your computer in order for Soy (our template language) to be compiled.

**Comment by MichKael** [comment]
okay!thanks

**Comment by zenorocha** [comment]
Yeah ;)
